#!/bin/bash

# Magic 8 Ball: A silly script to "answer" questions
# Copyright 2015  David Ulrich
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version="$1"
cmd=""
ext=""

if [ "$version" = "lua" ] || [ "$version" = "luajit" ] ; then
	cmd="lua"
	ext="lua"
elif [ "$version" = "node" ] || [ "$version" = "nodejs" ] || [ "$version" = "js" ]; then
	cmd="node"
	ext="js"
elif [ "$version" = "python" ] || [ "$version" = "py" ]; then
	cmd="python"
	ext="py"
elif [ "$version" = "ruby" ] || [ "$version" = "rb" ]; then
	cmd="ruby"
	ext="rb"
else
	echo "Unknown Magic 8 Ball version '$version'"
	exit 1
fi

$cmd "magic_8_ball.$ext"
